version: "2.2"

services:
  client:
    restart: on-failure
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server

  server:
    restart: on-failure
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  scraper:
    build:
      context: "./scraper"
      dockerfile: Dockerfile
    depends_on: 
      - torproxy
    
  torproxy:
    image: dperson/torproxy
